### ISSUE TITLE
Should use "Patch" instead of "Update" when changing k8s API Objects

### ISSUE THREAD

**Issue by davidz627** [kubernetes-csi/external-attacher#28] opened 2018-03-02 01:17 UTC
Currently when changing k8s API Objects the external attacher uses "Update" calls. These are less efficient than patching, they could also be problematic if there are small object changes in between Get and Update (accidental revert is possible).

They could also cause issue with mismatched API versions (this should not happen but we still want to minimize breakage/risk).

**Comment by jsafrane** [comment] 2018-03-02 09:05
Patches can overwrite something that was written by something else and attacher did not see it. In case of attacher it should be probably harmless and attacher should use patch with some caution. Any volunteer to rewrite the code?

**Comment by davidz627** [comment] 2018-03-02 21:15
Does `Update` not have this same issue?

**Comment by jsafrane** [comment] 2018-03-06 08:21
No, update checks ResourceVersion and returns `metav1.StatusReasonConflict` instead of overwriting newver version of object on API server. I was told that Path  could probably include ResourceVersion too to detect such conflict.

**Comment by verult** [comment] 2018-10-23 00:28
I'm seeing a test flake caused by PV Update calls not guarded by conflict retries here:
https://github.com/kubernetes-csi/external-attacher/blob/bce2b333e18417013170546eaff13b6241ccd903/pkg/controller/csi_handler.go#L198

We should either put a retry guard around the Update or change it to Patch

**Comment by pohly** [comment] 2018-10-23 06:12
Could this be the explanation for https://github.com/kubernetes/kubernetes/issues/65246?

**Comment by mariantalla** [comment] 2018-10-26 18:37
Hi, is this still in progress? Any blockers? 
Asking as [#65246](https://github.com/kubernetes/kubernetes/issues/65246) depends on it - and [#65246](https://github.com/kubernetes/kubernetes/issues/65246) is a release blocker at the moment.

cc @jberkus @mortent

**Comment by sbezverk** [comment] 2018-11-30 20:01
@jsafrane current test framework does not work well with Patch operation. Original approach is based on `core.NewUpdateAction` which accepts as one of the parameters a runtime object, it can easily be used to compare between expected and current object, as opposed to `core.NewPatchAction` which does not access the object, but requires `[]byte` containing the change. So to test it would seems one need 1. Run operation as a simulation to get `patch's []byte` and pass it to `core.NewPatchAction` as one of the parameters , 2. Let controller do the required action, 3. Compare  expected operation with reported one.

What if we do not track operations, but just the result, the final state of the object. In this case does not matter how the current object got into a specific state (Update/Patch/vi), as long as it is in the expected state, then the test would be a pass. 

I am curious what was the reason to track object updates on a verb level?

Appreciate some time to discuss different approaches..

**Comment by jsafrane** [comment] 2019-05-27 08:42
Fixed by #149.
/close

**Closed by jsafrane** 2019-05-27 08:42 UTC
Labels: help wanted, lifecycle/rotten
